"""Extract volunteer records from VAN volunteer-list PDFs.

The PDFs are text based (generated by iTextSharp) and laid out as a two column grid: the left
column carries name / "City, ST ZIP" / "age sex", and the right column carries the
Preferred/Home/Cell Phone labels with each value on the row beneath its label.

We read word coordinates via `pdftotext -bbox-layout` rather than plain text because the text
mode column offset differs per file (it sizes to the widest value), so a fixed character split
does not hold. Within a record, fields are addressed by their expected y-offset on the 11pt row
pitch -- not by row index -- because a missing phone value emits no line at all, which would
shift every later index.

Requires poppler's pdftotext on PATH (`brew install poppler`).
"""

from __future__ import annotations

import logging
import re
import subprocess
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

from solidaritytechtools.utils.normalize import normalize_phone

logger = logging.getLogger(__name__)

XHTML_NS: Final[str] = "{http://www.w3.org/1999/xhtml}"

ROW_PITCH_PT: Final[float] = 11.0
ROW_TOLERANCE_PT: Final[float] = 1.6
COLUMN_GAP_PT: Final[float] = 5.0

PREFERRED_PHONE_LABEL: Final[str] = "Preferred Phone"
PHONE_LABELS: Final[frozenset[str]] = frozenset({PREFERRED_PHONE_LABEL, "Home Phone", "Cell Phone"})

# Field positions within a record, as multiples of ROW_PITCH_PT below the record's anchor row.
# Labels sit at 0/2/4 and their values at 1/3/5, whether or not the value is present.
_NAME_ROW: Final[int] = 0
_LOCATION_ROW: Final[int] = 1
_AGE_SEX_ROW: Final[int] = 2
_PREFERRED_PHONE_ROW: Final[int] = 1
_HOME_PHONE_ROW: Final[int] = 3
_CELL_PHONE_ROW: Final[int] = 5

_LOCATION_RE: Final[re.Pattern[str]] = re.compile(
    r"^(?P<city>.*?),\s*(?P<state>[A-Z]{2})\s+(?P<zip5>\d{5})"
)
_AGE_SEX_RE: Final[re.Pattern[str]] = re.compile(r"^(?:(?P<age>\d{1,3})\s+)?(?P<sex>[MFU])$")

# Filename stem prefix -> the region the list covers.
REGION_BY_PREFIX: Final[dict[str, str]] = {
    "dane": "Dane",
    "mke": "Milwaukee",
    "bow": "BOW",
    "centralwi": "Central WI",
    "wow": "WOW",
}


@dataclass
class PdfVolunteer:
    """One person as listed in a volunteer-list PDF."""

    name: str
    first_name: str
    last_name: str
    city: str | None
    state: str | None
    zip5: str | None
    age: int | None
    sex: str | None
    phones: list[str] = field(default_factory=list)
    source_file: str = ""
    region: str | None = None


def region_for_file(path: Path | str) -> str | None:
    """Infer the region a volunteer list covers from its filename."""
    stem = re.sub(r"[^a-z]", "", Path(path).stem.lower())
    for prefix, region in REGION_BY_PREFIX.items():
        if stem.startswith(prefix):
            return region
    logger.warning(f"Could not infer a region from filename {Path(path).name}")
    return None


def split_name(name: str) -> tuple[str, str]:
    """
    Split a display name into (first, last) using the first and last whitespace-separated tokens.

    Middle names and multi-word surnames are common, and there is no reliable way to tell them
    apart here, so we take the outer tokens and let name normalization handle stray punctuation.
    """
    tokens = name.split()
    if not tokens:
        return "", ""
    if len(tokens) == 1:
        return tokens[0], ""
    return tokens[0], tokens[-1]


def _pdf_to_bbox_xml(path: Path) -> str:
    result = subprocess.run(
        ["pdftotext", "-bbox-layout", str(path), "-"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _page_lines(page: ET.Element) -> list[tuple[float, float, str]]:
    """Return (y, x, text) for every non-empty line on a page."""
    lines: list[tuple[float, float, str]] = []
    for line in page.iter(f"{XHTML_NS}line"):
        text = " ".join((word.text or "").strip() for word in line.iter(f"{XHTML_NS}word")).strip()
        if text:
            lines.append((float(line.get("yMin", 0.0)), float(line.get("xMin", 0.0)), text))
    return lines


def _row_text(rows: dict[float, str], target_y: float) -> str:
    """Look up the row nearest to target_y, or "" if nothing falls within tolerance."""
    best: float | None = None
    for y in rows:
        if abs(y - target_y) <= ROW_TOLERANCE_PT and (
            best is None or abs(y - target_y) < abs(best - target_y)
        ):
            best = y
    return rows[best] if best is not None else ""


def _phone_at(rows: dict[float, str], anchor_y: float, row: int) -> str | None:
    """Read a phone value, ignoring the label text that occupies the neighbouring rows."""
    text = _row_text(rows, anchor_y + row * ROW_PITCH_PT)
    if not text or text in PHONE_LABELS:
        return None
    return normalize_phone(text)


def parse_pdf(path: Path | str) -> list[PdfVolunteer]:
    """
    Extract every volunteer record from one volunteer-list PDF.

    params:
        path: the PDF to read

    returns: one PdfVolunteer per record, in document order
    """
    path = Path(path)
    region = region_for_file(path)
    root = ET.fromstring(_pdf_to_bbox_xml(path))

    volunteers: list[PdfVolunteer] = []
    for page in root.iter(f"{XHTML_NS}page"):
        lines = _page_lines(page)
        label_xs = [x for _, x, text in lines if text.startswith(PREFERRED_PHONE_LABEL)]
        if not label_xs:
            continue
        # The right column starts at the leftmost phone label; everything left of it is identity.
        column_split = min(label_xs) - COLUMN_GAP_PT

        left: dict[float, str] = {}
        right: dict[float, str] = {}
        for y, x, text in lines:
            (left if x < column_split else right)[round(y, 1)] = text

        anchors = sorted(y for y, text in right.items() if text == PREFERRED_PHONE_LABEL)
        for anchor in anchors:
            name = _row_text(left, anchor + _NAME_ROW * ROW_PITCH_PT)
            location = _row_text(left, anchor + _LOCATION_ROW * ROW_PITCH_PT)
            age_sex = _row_text(left, anchor + _AGE_SEX_ROW * ROW_PITCH_PT)

            city = state = zip5 = None
            if match := _LOCATION_RE.match(location):
                city = match.group("city").strip()
                state = match.group("state")
                zip5 = match.group("zip5")
            elif location:
                logger.debug(f"Unparsed location {location!r} in {path.name}")

            age = sex = None
            if match := _AGE_SEX_RE.match(age_sex.strip()):
                age = int(match.group("age")) if match.group("age") else None
                sex = match.group("sex")

            phones = [
                phone
                for row in (_PREFERRED_PHONE_ROW, _HOME_PHONE_ROW, _CELL_PHONE_ROW)
                if (phone := _phone_at(right, anchor, row))
            ]
            first_name, last_name = split_name(name)
            volunteers.append(
                PdfVolunteer(
                    name=name,
                    first_name=first_name,
                    last_name=last_name,
                    city=city,
                    state=state,
                    zip5=zip5,
                    age=age,
                    sex=sex,
                    phones=sorted(set(phones)),
                    source_file=path.name,
                    region=region,
                )
            )
    logger.info(f"Extracted {len(volunteers)} records from {path.name}")
    return volunteers


def parse_pdf_directory(directory: Path | str) -> list[PdfVolunteer]:
    """Extract volunteer records from every PDF in a directory, sorted by filename."""
    paths = sorted(Path(directory).glob("*.pdf"))
    if not paths:
        raise FileNotFoundError(f"No PDFs found in {directory}")
    volunteers: list[PdfVolunteer] = []
    for path in paths:
        volunteers.extend(parse_pdf(path))
    return volunteers


def count_records_in_pdf(path: Path | str) -> int:
    """
    Count records independently of the parser, for verification.

    Each record has exactly one "Preferred Phone" label, so counting those in plain text mode
    gives an expected record count that does not share any logic with parse_pdf.
    """
    result = subprocess.run(
        ["pdftotext", "-layout", str(path), "-"], capture_output=True, text=True, check=True
    )
    return result.stdout.count(PREFERRED_PHONE_LABEL)
